-- Reset draft data so players can be cleared (FK: picks -> players, teams, drafts)
BEGIN;

DELETE FROM picks;
DELETE FROM teams;
DELETE FROM drafts;
DELETE FROM players;

-- Insert all 187 players
INSERT INTO players (name, position, team, rank) VALUES
('Arvell Reese', 'LB/EDGE', 'Ohio State', 1),
('Caleb Downs', 'S', 'Ohio State', 2),
('Fernando Mendoza', 'QB', 'Indiana', 3),
('David Bailey', 'EDGE', 'Texas Tech', 4),
('Jeremiyah Love', 'RB', 'Notre Dame', 5),
('Sonny Styles', 'LB', 'Ohio State', 6),
('Rueben Bain Jr.', 'EDGE', 'Miami', 7),
('Francis Mauigoa', 'OT', 'Miami', 8),
('Carnell Tate', 'WR', 'Ohio State', 9),
('Mansoor Delane', 'CB', 'LSU', 10),
('Spencer Fano', 'OT', 'Utah', 11),
('Makai Lemon', 'WR', 'USC', 12),
('Jordyn Tyson', 'WR', 'Arizona State', 13),
('Monroe Freeling', 'OT', 'Georgia', 14),
('Vega Ioane', 'IOL', 'Penn State', 15),
('Dillon Thieneman', 'S', 'Oregon', 16),
('Jermod McCoy', 'CB', 'Tennessee', 17),
('Kenyon Sadiq', 'TE', 'Oregon', 18),
('Kadyn Proctor', 'OT', 'Alabama', 19),
('Keldric Faulk', 'EDGE', 'Auburn', 20),
('Akheem Mesidor', 'EDGE', 'Miami', 21),
('Avieon Terrell', 'CB', 'Clemson', 22),
('Caleb Lomu', 'OT', 'Utah', 23),
('Omar Cooper Jr.', 'WR', 'Indiana', 24),
('Peter Woods', 'DL', 'Clemson', 25),
('Emmanuel McNeil-Warren', 'S', 'Toledo', 26),
('KC Concepcion', 'WR', 'Texas A&M', 27),
('Denzel Boston', 'WR', 'Washington', 28),
('Kayden McDonald', 'DL', 'Ohio State', 29),
('Colton Hood', 'CB', 'Tennessee', 30),
('T.J. Parker', 'EDGE', 'Clemson', 31),
('Blake Miller', 'OT', 'Clemson', 32),
('Ty Simpson', 'QB', 'Alabama', 33),
('CJ Allen', 'LB', 'Georgia', 34),
('Cashius Howell', 'EDGE', 'Texas A&M', 35),
('Caleb Banks', 'DL', 'Florida', 36),
('Max Iheanachor', 'OT', 'Arizona State', 37),
('Zion Young', 'EDGE', 'Missouri', 38),
('Brandon Cisse', 'CB', 'South Carolina', 39),
('Emmanuel Pregnon', 'IOL', 'Oregon', 40),
('Chris Johnson', 'CB', 'San Diego State', 41),
('Jacob Rodriguez', 'LB', 'Texas Tech', 42),
('Anthony Hill Jr.', 'LB', 'Texas', 43),
('Christen Miller', 'DL', 'Georgia', 44),
('Jadarian Price', 'RB', 'Notre Dame', 45),
('Lee Hunter', 'DL', 'Texas Tech', 46),
('D''Angelo Ponds', 'CB', 'Indiana', 47),
('Chase Bisontis', 'IOL', 'Texas A&M', 48),
('R Mason Thomas', 'EDGE', 'Oklahoma', 49),
('Germie Bernard', 'WR', 'Alabama', 50),
('Malachi Lawrence', 'EDGE', 'UCF', 51),
('Gabe Jacas', 'EDGE', 'Illinois', 52),
('Eli Stowers', 'TE', 'Vanderbilt', 53),
('Chris Brazzell II', 'WR', 'Tennessee', 54),
('Keionte Scott', 'CB', 'Miami', 55),
('Chris Bell', 'WR', 'Louisville', 56),
('A.J. Haulcy', 'S', 'LSU', 57),
('Jake Golday', 'LB', 'Cincinnati', 58),
('Zachariah Branch', 'WR', 'Georgia', 59),
('Derrick Moore', 'EDGE', 'Michigan', 60),
('Dani Dennis-Sutton', 'EDGE', 'Penn State', 61),
('Caleb Tiernan', 'OT', 'Northwestern', 62),
('Treydan Stukes', 'CB', 'Arizona', 63),
('Gennings Dunker', 'OT', 'Iowa', 64),
('Antonio Williams', 'WR', 'Clemson', 65),
('Josiah Trotter', 'LB', 'Missouri', 66),
('Keith Abney II', 'CB', 'Arizona State', 67),
('Mike Washington Jr.', 'RB', 'Arkansas', 68),
('Keylan Rutledge', 'IOL', 'Georgia Tech', 69),
('Connor Lew', 'IOL', 'Auburn', 70),
('Malachi Fields', 'WR', 'Notre Dame', 71),
('Kamari Ramsey', 'S', 'USC', 72),
('Romello Height', 'EDGE', 'Texas Tech', 73),
('Joshua Josephs', 'EDGE', 'Tennessee', 74),
('Max Klare', 'TE', 'Ohio State', 75),
('Domonique Orange', 'DL', 'Iowa State', 76),
('Elijah Sarratt', 'WR', 'Indiana', 77),
('Kyle Louis', 'LB', 'Pittsburgh', 78),
('Ted Hurst', 'WR', 'Georgia State', 79),
('Davison Igbinosun', 'CB', 'Ohio State', 80),
('Genesis Smith', 'S', 'Arizona', 81),
('Malik Muhammad', 'CB', 'Texas', 82),
('Sam Hecht', 'IOL', 'Kansas State', 83),
('Gracen Halton', 'DL', 'Oklahoma', 84),
('Skyler Bell', 'WR', 'UConn', 85),
('Darrell Jackson Jr.', 'DL', 'Florida State', 86),
('Bud Clark', 'S', 'TCU', 87),
('Deion Burks', 'WR', 'Oklahoma', 88),
('Daylen Everette', 'CB', 'Georgia', 89),
('Chandler Rivers', 'CB', 'Duke', 90),
('Jake Slaughter', 'IOL', 'Florida', 91),
('LT Overton', 'EDGE', 'Alabama', 92),
('Zakee Wheatley', 'S', 'Penn State', 93),
('Bryce Lance', 'WR', 'North Dakota State', 94),
('Jonah Coleman', 'RB', 'Washington', 95),
('Garrett Nussmeier', 'QB', 'LSU', 96),
('Jalon Kilgore', 'S', 'South Carolina', 97),
('Ja''Kobi Lane', 'WR', 'USC', 98),
('Keyron Crawford', 'EDGE', 'Auburn', 99),
('Deontae Lawson', 'LB', 'Alabama', 100),
('Logan Jones', 'IOL', 'Iowa', 101),
('Jalen Farmer', 'IOL', 'Kentucky', 102),
('Emmett Johnson', 'RB', 'Nebraska', 103),
('Julian Neal', 'CB', 'Arkansas', 104),
('Austin Barber', 'OT', 'Florida', 105),
('Devin Moore', 'CB', 'Florida', 106),
('Jaishawn Barham', 'LB', 'Michigan', 107),
('Will Lee III', 'CB', 'Texas A&M', 108),
('Tacario Davis', 'CB', 'Washington', 109),
('Kage Casey', 'OT', 'Boise State', 110),
('Justin Joly', 'TE', 'NC State', 111),
('Brenen Thompson', 'WR', 'Mississippi State', 112),
('Sam Roush', 'TE', 'Stanford', 113),
('Michael Trigg', 'TE', 'Baylor', 114),
('Drew Shelton', 'OT', 'Penn State', 115),
('Oscar Delp', 'TE', 'Georgia', 116),
('Domani Jackson', 'CB', 'Alabama', 117),
('Chris McClellan', 'DL', 'Missouri', 118),
('De''Zhaun Stribling', 'WR', 'Ole Miss', 119),
('Anthony Lucas', 'EDGE', 'USC', 120),
('Billy Schrauth', 'IOL', 'Notre Dame', 121),
('Dametrious Crownover', 'OT', 'Texas A&M', 122),
('Eli Raridon', 'TE', 'Notre Dame', 123),
('Jude Bowry', 'OT', 'Boston College', 124),
('Drew Allar', 'QB', 'Penn State', 125),
('Carson Beck', 'QB', 'Miami', 126),
('Dontay Corleone', 'DL', 'Cincinnati', 127),
('Brian Parker II', 'IOL', 'Duke', 128),
('Rayshaun Benny', 'DL', 'Michigan', 129),
('Parker Brailsford', 'IOL', 'Alabama', 130),
('Taylen Green', 'QB', 'Arkansas', 131),
('Zane Durant', 'DL', 'Penn State', 132),
('Harold Perkins Jr.', 'LB', 'LSU', 133),
('Matt Gulbin', 'IOL', 'Michigan State', 134),
('Markel Bell', 'OT', 'Miami', 135),
('DeMonte Capehart', 'DL', 'Clemson', 136),
('Kaleb Proctor', 'DL', 'Southeastern Louisiana', 137),
('Demond Claiborne', 'RB', 'Wake Forest', 138),
('Zxavian Harris', 'DL', 'Ole Miss', 139),
('Isaiah World', 'OT', 'Oregon', 140),
('Tyreak Sapp', 'EDGE', 'Florida', 141),
('Dallen Bentley', 'TE', 'Utah', 142),
('Nicholas Singleton', 'RB', 'Penn State', 143),
('Seth McGowan', 'RB', 'Kentucky', 144),
('Kaytron Allen', 'RB', 'Penn State', 145),
('CJ Daniels', 'WR', 'Miami', 146),
('Fa''alili Fa''amoe', 'OT', 'Wake Forest', 147),
('Joe Royer', 'TE', 'Cincinnati', 148),
('Kendrick Law', 'WR', 'Kentucky', 149),
('Cole Payton', 'QB', 'North Dakota State', 150),
('Bryce Boettcher', 'LB', 'Oregon', 151),
('Trey Zuhn III', 'OT', 'Texas A&M', 152),
('Kevin Coleman Jr.', 'WR', 'Missouri', 153),
('Jack Endries', 'TE', 'Texas', 154),
('Nadame Tucker', 'EDGE', 'Western Michigan', 155),
('Kaelon Black', 'RB', 'Indiana', 156),
('Jaydn Ott', 'RB', 'Oklahoma', 157),
('John Michael Gyllenborg', 'TE', 'Wyoming', 158),
('Charles Demmings', 'CB', 'Stephen F. Austin', 159),
('Reggie Virgil', 'WR', 'Texas Tech', 160),
('J.C. Davis', 'OT', 'Illinois', 161),
('Cade Klubnik', 'QB', 'Clemson', 162),
('Jager Burton', 'IOL', 'Kentucky', 163),
('Taurean York', 'LB', 'Texas A&M', 164),
('Nate Boerkircher', 'TE', 'Texas A&M', 165),
('Max Llewellyn', 'EDGE', 'Iowa', 166),
('Landon Robinson', 'DL', 'Navy', 167),
('Tim Keenan III', 'DL', 'Alabama', 168),
('Hezekiah Masses', 'CB', 'California', 169),
('Ethan Burke', 'EDGE', 'Texas', 170),
('Michael Taaffe', 'S', 'Texas', 171),
('Devon Marshall', 'CB', 'NC State', 172),
('VJ Payne', 'S', 'Kansas State', 173),
('Kaleb Elarms-Orr', 'LB', 'TCU', 174),
('Eric Rivers', 'WR', 'Georgia Tech', 175),
('Ephesians Prysock', 'CB', 'Washington', 176),
('Louis Moore', 'S', 'Indiana', 177),
('DJ Campbell', 'IOL', 'Texas', 178),
('Skyler Gill-Howard', 'DL', 'Texas Tech', 179),
('Aiden Fisher', 'LB', 'Indiana', 180),
('Beau Stephens', 'IOL', 'Iowa', 181),
('Jeremiah Wright', 'IOL', 'Auburn', 182),
('Josh Cameron', 'WR', 'Baylor', 183),
('Cyrus Allen', 'WR', 'Cincinnati', 184),
('Marlin Klein', 'TE', 'Michigan', 185),
('Aaron Anderson', 'WR', 'LSU', 186),
('Vincent Anthony Jr.', 'EDGE', 'Duke', 187);

COMMIT;